# Generated by Django 5.2.17 on 2026-09-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('student_age', models.IntegerField()),
                ('student_city', models.CharField(max_length=150)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=20)),
                ('student_subject', models.CharField(max_length=100)),
                ('student_grade', models.CharField(max_length=20)),
                ('student_hobby', models.CharField(max_length=100)),
                ('student_address', models.CharField(max_length=200)),
                ('enrollment_year', models.IntegerField()),
            ],
        ),
    ]
